#ifndef FONTSVG_APP_VERSION_H_
#define FONTSVG_APP_VERSION_H_

#define FONTSVG_VERSION_MAJOR 0
#define FONTSVG_VERSION_MINOR 1
#define FONTSVG_VERSION_PATCH 0
#define FONTSVG_VERSION_BUILD 0
#define FONTSVG_VERSION_STR_A "0.1.0"

#endif
